### PR TITLE
allow runtime resolution of app url

### PR DESCRIPTION
**Pull request by cdaguerre**
This allows inferring the service-provider urls during runtime, rather than "hard-coding" them.
One could argue that runtime configuration is also possible through the use of env vars, eg.:
```yaml
sp:
    entityId: '%env(APP_URL)%/saml/metadata' 
    assertionConsumerService:
        url: '%env(APP_URL)%/saml/acs'
    singleLogoutService:
        url: '%env(APP_URL)%/saml/acs'
```
But: 
1/ this requires the environment variables to be set ;)
2/ I can't think of a case where they wouldn't match the current request's host so I'm not sure this needs to be configurable at all (but maybe I'm missing something?)

I think it makes sense to have sensible defaults in the bundle's configuration, still allowing to change things.
This is also much more convenient during development because it just works, regardless of the scheme (TLS or not), port and host of your dev server (even localhost) without having to configure anything at all.

As a side note, we've been using the hslavich bundle for years maintaining our own fork to achieve this through service decoration and to address other issues than this bundle has addressed (like the hardcoded firewall name in the login controller for example). This is the last pain point for us ;)

### CODE REVIEW

**Comment by a-menshchikov** [comment]
@cdaguerre hello!
Could you please explain your use case where you need it?

**Comment by cdaguerre** [comment]
> @cdaguerre hello! Could you please explain your use case where you need it?

Hi @a-menshchikov sorry for opening the PR without a description, I updated the description.

**Comment by a-menshchikov** [comment]
@cdaguerre thank you for detailed description!

I have made another PR (#8) where using service factory for `Auth` instantiating instead of extending of original Auth class. This approach looks more conventional for me and want to know your opinion.

Also I've renamed `<request_host>` to `<request_scheme_and_host>` and used `Symfony\Component\HttpFoundation\Request::getSchemeAndHttpHost` instead of composing of this value by myself.

Let me know if I can close this PR in favor of #8.

**Comment by cdaguerre** [comment]
@a-menshchikov #8  is indeed a far cleaner approach, thank you very much!!

**Pull request closed without merging**
