### PR TITLE
Allow to override AuthRegistry

### PR DESCRIPTION
**Pull request by podhy**
This PR allows to change AuthRegistry implementation.

It changes getDefinition to findDefinition in AuthRegistryCompilerPass which allows to search for aliases.

### CODE REVIEW

**Comment by a-menshchikov** [comment]
Hi @podhy. 
Could you explain why do you need to get the definition by the alias?

**Comment by podhy** [comment]
Hi @a-menshchikov ,
I would like to replace AuthRegistry with my own implementation, which can return SAML configuration which is defined in external source.

I know I can replace implementation using CompilerPassInterface in Kernel, but this is more elegant.

**Comment by a-menshchikov** [comment]
@podhy you can override default AuthRegistry with your implementation by the following config:
```yaml
services:
  # ...
  Nbgrp\OneloginSamlBundle\Onelogin\AuthRegistryInterface:
    class: 'App\YourAuthRegistry'
```
Or you cannot doing this way?

**Comment by podhy** [comment]
@a-menshchikov yes this was first thing I made. I added into services.yaml

```
Nbgrp\OneloginSamlBundle\Onelogin\AuthRegistryInterface: '@App\AuthRegistry'
```

But this throws following exception:
image

My PR fixes this and allows to override registry

Tested on Symfony 6.2.6 - but this is Symfony version independent

**Comment by a-menshchikov** [comment]
@podhy you right about an error — you replace service ID "Nbgrp\OneloginSamlBundle\Onelogin\AuthRegistryInterface" by the alias to your service with the same name and this leads the error when the AuthRegistryCompilerPass try to get definition of the service this such ID.

You just need to override class for "Nbgrp\OneloginSamlBundle\Onelogin\AuthRegistryInterface" service ID. Try the config I suggested above.

**Comment by a-menshchikov** [comment]
@podhy I close this PR because it seems you tried to override the AuthRegistry in a wrong way.

**Pull request closed without merging**
